version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - DATABASE_URL=mysql://root:password@db:3306/netflix_spotify_marketplace
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=random-secret-key
    ports:
      - "3000:3000"
    volumes:
      - ./public:/app/public
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=netflix_spotify_marketplace
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data: 